name: Flutter Web Build & FTP Upload

on:
  workflow_run:
      workflows: ["Flutter Code Quality & Production Check"]
      types:
        - completed
  workflow_dispatch:

jobs:
  build_and_upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "PUB_CACHE=$HOME/.pub-cache" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload to FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PATH: ${{ secrets.FTP_PATH }}
        run: |
          echo "üåê Uploading Flutter Web build to FTP..."
          lftp -u "$FTP_USER","$FTP_PASSWORD" "$FTP_HOST" <<EOF
          mirror -R build/web $FTP_PATH --delete --parallel=2
          quit
          EOF
          echo "‚úÖ Upload finished"
