name: Flutter Web Build & FTP Upload

on:
  workflow_run:
    workflows: ["Flutter Code Quality & Production Check"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build_and_upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "PUB_CACHE=$HOME/.pub-cache" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web
          server-dir: /
          protocol: ftps
          port: 21
